development:
    cloudinary_cloud_name: <%= ENV["deq4oqjip"] %>
    cloudinary_api_key: <%= ENV["134342859114186"] %>
    cloudinary_api_secret: <%= ENV["KXkNAhIUsPYqig7l_QU6JSvOyOw"] %>
test:
    cloudinary_cloud_name: <%= ENV["deq4oqjip"] %>
    cloudinary_api_key: <%= ENV["134342859114186"] %>
    cloudinary_api_secret: <%= ENV["KXkNAhIUsPYqig7l_QU6JSvOyOw"] %>
production:
    cloudinary_cloud_name: <%= ENV["deq4oqjip"] %>
    cloudinary_api_key: <%= ENV["134342859114186"] %>
    cloudinary_api_secret: <%= ENV["KXkNAhIUsPYqig7l_QU6JSvOyOw"] %>