Admin.destroy_all
a1 = Admin.create(:username => 'Yelena', :email => 'channon.y@gmail.com.au', :image => 'https://static.wikia.nocookie.net/marvel_dc/images/7/7d/Transmetropolitan_Vol_1_46.jpg', :password => "password")
a2 = Admin.create(:username => 'Spider Jerusalem', :email => 'spider.j@gmail.com.au', :image => 'https://ihatehate.files.wordpress.com/2015/05/spider-useless-bastards.jpg', :password => "password")
a3 = Admin.create(:username => 'Cat', :email => 'cat@gmail.com.au', :image => 'https://comicvine1.cbsistatic.com/uploads/scale_small/0/1808/210883-140144-cat.jpg', :password => "password")
a4 = Admin.create(:username => 'Jamie Hewlett',  :email => 'jamie.h@gmail.com.au', :image => 'https://www.economist.com/img/b/1000/563/90/sites/default/files/20180707_BLP531.jpg', :password => "password")
a5 = Admin.create(:username => 'Tank Girl', :email => 'booga@gmail.com.au', :image => 'https://cnet1.cbsistatic.com/img/JVowmFoaOxK_wg6P3rTSy5cv7_E=/1092x0/2019/09/10/7528a787-67c9-479f-afd0-b2a02f0811c8/tankgirl1.jpg', :password => "password")
 puts "#{ Admin.count } admins created"
# 
 Resource.destroy_all
r1 = Resource.create :title => 'Mask Off Masculinity Redefined', :resource_type => 'Book', :image => "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/6744/9780674430006.jpg", :description => "https://www.youtube.com/watch?v=reyy9ASpMSc"
r2 = Resource.create :title => 'Automation and the future of work', :resource_type => 'Book', :image => 'https://cdn-ed.versobooks.com/images/000015/555/Automation_and_the_Future_of_Work-9aef0ca3e954a61b69a5b4b4f1c4b3d4.png', :description => 'Automation isn’t a new topic, just ask Ford, but the mass scale impact it is going to have on us and our kid’s generations necessitates a genuine new discussion of who owns what, how and why. Whilst the title may suggest otherwise, I found this book relatively easy to read and it is easily understandable to anyone with entry level criticisms of capitalism. It’s a highly qualitative argument for the invention of new collective capacities in a world in which work should no longer be central to life itself.'
r3 = Resource.create :title => 'The Management of Savagery', :resource_type => "Book", :image => "https://cdn-ed.versobooks.com/images/000015/360/9781788732307-0163848f62ce9dd830a29259cf9b27fe.jpg", :description => "How America's National Security State Fueled the Rise of Al Qaeda, ISIS, and Donald Trump."
r4 = Resource.create :title => 'Moby Dick', :resource_type => 'Place to Sleep', :image => 'https://cdn2.penguin.com.au/covers/original/9780099511182.jpg', :description => "Literally, what a beast of a book! It amuses me to this day that the initial reaction and reviews of this masterpiece were anything but positive, quite destructive to be fair. I do believe it is fair to call this the greatest American book written at this point, the sheer skill and enjoyable prose is second to none. Granted, the esoteric subject matter can create an aura of difficulty that too often keeps readers at bay, let alone the length of the novel but if anyone needed convincing, one of the greatest metal bands of modern times, Mastodon, even wrote an entire concept album about Ishmael, Ahab and the Great Whale. To those unaware, Moby Dick is an 1851 novel by American writer Herman Melville. The book is the sailor Ishmael's narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale that on the ship's previous voyage bit off Ahab's leg at the knee."
r5 = Resource.create :title => 'The Master and Margarita', :resource_type => 'Place to Sleep', :image => 'https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F5e148d24-9044-4b36-8fc4-85aced43a194_689x429.png', :description => 'I can never decide if Moby Dick or this absolute masterpiece is my favourite book of all time. For the uninitiated readers of Russian Fiction, it goes a little something like this: The Devil has come to town, Stalinist Moscow that is but don’t worry– all he wants to do is stage a magic show. This absurd premise forms the central plot of Mikhail Bulgakov’s masterpiece, “The Master and Margarita.” Its blend of political satire, historical fiction and occult mysticism has earned a legacy as one of the 20th century’s greatest novels– and one of its strangest. Truly, the journey of this book not only brilliantly describes life under Stalin - this book was only available as a highly censored version until 1966 I believe, and for that alone it is worth the read, but explores the absurdity of Satan, Cats, Atheism and Stalinist Soviet Life. I truly cannot get enough of this one.' 
r6 = Resource.create :title => 'Q', :resource_type => 'Book', :image => 'https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F3345a966-72de-41a5-ba2a-7fb7689437d9_643x483.png', :description => "Ok, now that my two favourite classics are out of the way, god damn, read this book!! Especially, if you are into history and additionally into the type of politics that I am into - this will be a game changer. The book follows the journey of an Anabaptist radical across Europe in the first half of the 16th century as he joins in various movements and uprisings that come as a result of the Protestant reformation. The book spans 30 years as he is pursued by 'Q' (short for 'Qoèlet'), a spy for the Roman Catholic Church cardinal Giovanni Pietro Carafa. The main character, who changes his name many times during the story, first fights in the German Peasants' War beside Thomas Müntzer, during which time he takes part in negotiations which are eventually formalised as the Twelve Articles. Following this, he battles in Münster's siege, during the Münster Rebellion, and some years later, in Venice. It essentially the story of the deeply rooted anarchism in the European Cultural context that could have been a pivotal turning point in our world, crazy part is, all of this actually happened."
r7 = Resource.create :title => 'The Swarm', :resource_type => "Shelter", :image => "https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F0223b8f6-4042-4bc5-834f-cb76d7eba972_689x371.png", :description => "Up until a few days ago I didn’t realize there was an English translation of this book and I am so incredibly happy that there is one. I have probably read this monster of a science fiction novel 4 or 5 times and it just gets better and better. German in the original the novel borrows some ideas from the Gaia Theory. It hits on the notion that mankind's activities have created conditions that begin to affect a delicate equilibrium of biotic and abiotic conditions that have fostered and sustained complex life forms and ecosystems and they have had enough of us. It comes with a heavy reference section citing more scientific material that I have read in my lifetime and yes, more subplots that initially might be a little confusing but come together in a finale that continues to blow my mind."
r8 = Resource.create :title => 'State of Fear', :resource_type => "Place to Eat", :image => "https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F5f289cfd-e65c-4b42-a1e2-182067763a9d_362x209.png", :description => "Yes, the “Jurassic Park” Michael Crichton, who just so happens to have written a plethora of books outside that huge piece of commercial success that mostly can be found in my library. “State of Fear” plot essentially revolves around the story in which eco-terrorists plot mass murder to publicize the danger of global warming. Despite being a work of fiction, the book contains many graphs and footnotes, two appendices, and a 20-page bibliography in support of Crichton's beliefs about global warming, most of which I don’t necessarily agree with but the important being here being that it offers a different perspective of the industry of activism - and that is the hugely important notion of this book. It is a riveting read, no questions asked, but the underlying analysis and criticism of the industry of activism has always stuck with me. If none of these tickle your fancy, just pick up any book by Terry Pratchett - possibly the greatest modern Humanist we have had and whose books, yes, all of them have been read over and over again, have read to my kid and will continue to champion."
r9 = Resource.create :title => 'Fully Automated Luxury Communism by Aaron Bastani', :resource_type => 'Shelter', :image => 'https://cdn-ed.versobooks.com/images/000015/644/bastani_falc-85803d0e668b2424aed9411c99350e4c.png', :description => 'I’d wager that most of us probably recognize a version of this title from any number of amusing memes and if you have ever wondered where those came from, here you are. This is wonderful utopian, yet scientific book for anyone interested in a reason based approach to what our future could look like. Aaron Bastani conjures a vision of extraordinary hope, showing how we move to energy abundance, feed a world of 9 billion, overcome work, transcend the limits of biology, and establish meaningful freedom for everyone. Buy here: https://www.versobooks.com/books/3156-fully-automated-luxury-communism'
r10 = Resource.create :title => 'The Woman Rebel, No Gods, No Masters', :resource_type => "Place to Sleep", :image => "https://upload.wikimedia.org/wikipedia/commons/1/15/NoGodsNoMasters.jpg", :description => "https://en.wikipedia.org/wiki/No_gods,_no_masters"
r11 = Resource.create :title => 'The Value of Everything', :resource_type => 'Video', :image => "https://www.penguin.co.uk/content/dam/prh/books/280/280466/9780141980768.jpg.transform/PRHDesktopWide_small/image.jpg", :description => "Watch this to gain more insight into the book The Value of Everything 'https://www.penguin.co.uk/books/280/280466/the-value-of-everything/9780141980768.html' "
 puts "#{ Resource.count } resources added."

# ## ASSOCIATIONS ##
 
puts "Admins and Resources."
a1.resources << r1 << r6
a2.resources << r2 << r7
a3.resources << r3 << r8
a4.resources << r4 << r9 << r11
a5.resources << r5 << r10